'use client';

import { useMemo, useState } from 'react';
import { Crown, FileInput, Globe2, Instagram, Linkedin, Mail, MapPinned, MessageSquare, Rocket, Search, Send, Sparkles, Upload, Users, X, Zap } from 'lucide-react';
import type { CampaignInput, DemoQuality, LeadSource, OutreachChannel } from '@/lib/types';
import { generateAlgorithmicKeywords } from '@/lib/pipeline';

interface NewCampaignModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLaunch: (input: CampaignInput) => Promise<void>;
  loading: boolean;
}

const sourceOptions: Array<{ value: LeadSource; label: string; icon: React.ElementType }> = [
  { value: 'instagram', label: 'Instagram (Apify)', icon: Instagram },
  { value: 'google_maps', label: 'Google Maps', icon: MapPinned },
  { value: 'url_list', label: 'URLs', icon: Globe2 },
  { value: 'csv', label: 'CSV', icon: Upload },
  { value: 'linkedin', label: 'LinkedIn', icon: Linkedin },
  { value: 'product_hunt', label: 'Product Hunt', icon: Rocket }
];

const channelOptions: Array<{ value: OutreachChannel; label: string; icon: React.ElementType; desc: string }> = [
  { value: 'email', label: 'Email (Resend)', icon: Mail, desc: 'HTML proposal with live demo button' },
  { value: 'sms', label: 'SMS (Twilio)', icon: MessageSquare, desc: 'Direct 1-tap text with live demo link' },
  { value: 'multi', label: 'Multi (Email + SMS)', icon: Zap, desc: 'Maximum response rate' },
  { value: 'linkedin', label: 'LinkedIn', icon: Linkedin, desc: 'Custom connection pitch' }
];

const limitPresets = [5, 10, 25, 50, 100, 250];

export function NewCampaignModal({ isOpen, onClose, onLaunch, loading }: NewCampaignModalProps) {
  const [form, setForm] = useState<CampaignInput>({
    audience: 'High-ticket wellness clinics with weak mobile booking',
    locations: 'Austin, TX',
    source: 'google_maps',
    sourcePayload: '',
    demoType: 'website',
    channel: 'email',
    limit: 10,
    autoGenerateDemos: true,
    demoQuality: 'low'
  });

  // Real-time preview of multi-keyword search queries generated for campaign
  const keywordPreview = useMemo(() => {
    return generateAlgorithmicKeywords(form);
  }, [form]);

  if (!isOpen) return null;

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    await onLaunch(form);
    onClose();
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="panel bg-white max-w-xl w-full p-5 shadow-2xl relative animate-in fade-in zoom-in-95 duration-200 max-h-[90vh] flex flex-col overflow-hidden">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-1.5 rounded-full hover:bg-gray-100 text-gray-400 hover:text-gray-600 z-10 transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-2.5 mb-3 flex-shrink-0">
          <div className="w-9 h-9 rounded-xl bg-blue-600 text-white flex items-center justify-center font-bold shadow-md shadow-blue-500/20">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h2 className="text-base font-extrabold text-gray-900 leading-tight">Launch Multi-Keyword Campaign</h2>
            <p className="text-[11px] text-gray-500 font-medium">Scrape leads, auto-generate v0 AI sites, and dispatch outreach</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="flex-1 flex flex-col min-h-0">
          <div className="flex-1 overflow-y-auto pr-1 space-y-3.5 pb-2 scrollbar-thin">
            <div>
              <label className="label">Target Audience & Niche</label>
              <input
                type="text"
                value={form.audience}
                onChange={(e) => setForm({ ...form, audience: e.target.value })}
                className="field text-xs py-2"
                placeholder="e.g. Wellness clinics, B2B SaaS, Dental practices"
                required
              />
            </div>

            <div>
              <label className="label">Target Locations</label>
              <input
                type="text"
                value={form.locations}
                onChange={(e) => setForm({ ...form, locations: e.target.value })}
                className="field text-xs py-2"
                placeholder="e.g. Austin, TX; Dallas, TX"
              />
            </div>

            {/* Outreach Channel Selection */}
            <div>
              <label className="label">Primary Outreach Channel</label>
              <div className="grid grid-cols-2 gap-2">
                {channelOptions.map((ch) => {
                  const Icon = ch.icon;
                  const selected = form.channel === ch.value;
                  return (
                    <div
                      key={ch.value}
                      onClick={() => setForm({ ...form, channel: ch.value })}
                      className={`p-2.5 rounded-xl border cursor-pointer transition-all ${
                        selected
                          ? 'bg-blue-50 border-blue-500 shadow-sm'
                          : 'bg-white border-gray-200 hover:bg-gray-50'
                      }`}
                    >
                      <div className="flex items-center gap-1.5 font-extrabold text-xs text-gray-900">
                        <Icon className="w-3.5 h-3.5 text-blue-600" />
                        <span>{ch.label}</span>
                      </div>
                      <p className="text-[10px] text-gray-500 mt-0.5 leading-tight">{ch.desc}</p>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Auto Generate v0 Demos Toggle & Mode Selector */}
            <div className="p-3.5 rounded-2xl bg-gray-50/80 border border-gray-200/70 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-7 h-7 rounded-lg bg-blue-50 text-blue-600 border border-blue-100 flex items-center justify-center">
                    <Sparkles className="w-3.5 h-3.5" />
                  </div>
                  <div>
                    <div className="text-xs font-extrabold text-gray-900">Auto-Generate v0 AI Demos</div>
                    <div className="text-[10px] text-gray-500">Automatically build live demo sites for qualified leads</div>
                  </div>
                </div>
                <input
                  type="checkbox"
                  checked={form.autoGenerateDemos !== false}
                  onChange={(e) => setForm({ ...form, autoGenerateDemos: e.target.checked })}
                  className="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500 cursor-pointer"
                />
              </div>

              {form.autoGenerateDemos !== false && (
                <div className="pt-2.5 border-t border-gray-200/70">
                  <div className="text-[10px] font-extrabold uppercase tracking-wider text-gray-400 mb-2 flex items-center justify-between">
                    <span>Demo Quality & Generation Mode</span>
                    <span className="font-semibold text-gray-600">
                      {form.demoQuality === 'high' ? 'v0-pro (High-End)' : 'v0-mini (Standard)'}
                    </span>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      type="button"
                      onClick={() => setForm({ ...form, demoQuality: 'low' })}
                      className={`p-2.5 rounded-xl border text-left transition-all ${
                        form.demoQuality !== 'high'
                          ? 'bg-white border-blue-500 ring-1 ring-blue-500/20 shadow-xs'
                          : 'bg-white/60 border-gray-200 text-gray-600 hover:bg-white'
                      }`}
                    >
                      <div className="flex items-center gap-1.5 font-extrabold text-xs text-gray-900">
                        <Zap className="w-3.5 h-3.5 text-gray-500" />
                        <span>Low Usage (Fast)</span>
                      </div>
                      <div className="text-[10px] text-gray-500 mt-0.5 leading-snug">
                        Clean responsive layout, core services & booking form (v0-mini)
                      </div>
                    </button>

                    <button
                      type="button"
                      onClick={() => setForm({ ...form, demoQuality: 'high' })}
                      className={`p-2.5 rounded-xl border text-left transition-all ${
                        form.demoQuality === 'high'
                          ? 'bg-white border-blue-500 ring-1 ring-blue-500/20 shadow-xs'
                          : 'bg-white/60 border-gray-200 text-gray-600 hover:bg-white'
                      }`}
                    >
                      <div className="flex items-center gap-1.5 font-extrabold text-xs text-gray-900">
                        <Crown className="w-3.5 h-3.5 text-blue-600" />
                        <span>High-End (Pro)</span>
                      </div>
                      <div className="text-[10px] text-gray-500 mt-0.5 leading-snug">
                        Flagship layout, quote calculator & booking drawer (v0-pro)
                      </div>
                    </button>
                  </div>
                </div>
              )}
            </div>

            {/* Option: Max Prospects to Find */}
            <div>
              <label className="label flex items-center justify-between">
                <span className="flex items-center gap-1.5 text-gray-900 font-extrabold">
                  <Users className="w-3.5 h-3.5 text-blue-600" />
                  <span>Max Leads to Find for Campaign</span>
                </span>
                <span className="text-[10px] text-gray-500 font-semibold">
                  Limit: {form.limit} lead{form.limit === 1 ? '' : 's'}
                </span>
              </label>
              <div className="grid grid-cols-6 gap-1.5 mt-1">
                {limitPresets.map((preset) => (
                  <button
                    key={preset}
                    type="button"
                    onClick={() => setForm({ ...form, limit: preset })}
                    className={`py-1.5 rounded-xl text-xs font-bold border transition-all ${
                      form.limit === preset
                        ? 'bg-blue-600 text-white border-blue-600 shadow-sm'
                        : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-50'
                    }`}
                  >
                    {preset}
                  </button>
                ))}
              </div>
              <div className="mt-1.5 flex items-center gap-2">
                <span className="text-[11px] text-gray-500 font-medium">Or custom count:</span>
                <input
                  type="number"
                  min={1}
                  max={250}
                  value={form.limit}
                  onChange={(e) =>
                    setForm({
                      ...form,
                      limit: Math.min(Math.max(Number(e.target.value) || 1, 1), 250)
                    })
                  }
                  className="field text-xs w-20 py-1 font-extrabold text-blue-700"
                />
              </div>
            </div>

            {/* Multi-Keyword Expansion Preview */}
            <div className="p-2.5 rounded-xl bg-blue-50/60 border border-blue-100">
              <div className="flex items-center gap-1.5 text-xs font-extrabold text-blue-900 mb-1">
                <Search className="w-3.5 h-3.5 text-blue-600" />
                <span>Multi-Keyword Search Query Expansion ({keywordPreview.length} queries)</span>
              </div>
              <div className="flex flex-wrap gap-1 max-h-24 overflow-y-auto">
                {keywordPreview.map((kw, i) => (
                  <span
                    key={i}
                    className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-white text-blue-700 border border-blue-200/80 shadow-xs"
                  >
                    {kw}
                  </span>
                ))}
              </div>
            </div>

            <div>
              <label className="label">Lead Discovery Source</label>
              <div className="grid grid-cols-3 gap-1.5">
                {sourceOptions.map((opt) => {
                  const Icon = opt.icon;
                  const selected = form.source === opt.value;
                  return (
                    <button
                      key={opt.value}
                      type="button"
                      onClick={() => setForm({ ...form, source: opt.value })}
                      className={`flex items-center justify-center gap-1.5 py-1.5 px-2.5 rounded-xl border text-xs font-bold transition-all ${
                        selected
                          ? 'bg-blue-50 border-blue-500 text-blue-700 shadow-sm'
                          : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-50'
                      }`}
                    >
                      <Icon className="w-3.5 h-3.5" />
                      <span>{opt.label}</span>
                    </button>
                  );
                })}
              </div>
            </div>

            <div>
              <label className="label">Source Data / Prospects List (Optional)</label>
              <textarea
                rows={2}
                value={form.sourcePayload}
                onChange={(e) => setForm({ ...form, sourcePayload: e.target.value })}
                className="field text-xs resize-none py-1.5"
                placeholder="Paste Instagram usernames/URLs (e.g. @company or instagram.com/brand), CSV rows, or leave blank to auto-scrape real leads."
              />
            </div>
          </div>

          <div className="-mx-5 -mb-5 px-5 py-3.5 bg-gray-50/90 border-t border-gray-100 flex items-center justify-end gap-3 flex-shrink-0 backdrop-blur-xs">
            <button
              type="button"
              onClick={onClose}
              className="btn secondary text-xs py-2 px-4"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={loading}
              className="btn text-xs px-6 py-2 shadow-lg shadow-blue-500/20"
            >
              {loading ? 'Scraping & Building v0 AI Sites...' : `Launch Campaign (${form.limit} Leads)`}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
