import type { SupabaseClient } from '@supabase/supabase-js';
import { generateCampaignKeywordsAnthropic, analyzeLeadWithAnthropic } from '@/lib/anthropic';
import { discoverProspects } from '@/lib/discovery';
import { analyzeLeadWithGemini, generateCampaignKeywords } from '@/lib/gemini';
import { generateVertexCampaignKeywords, analyzeLeadWithVertex } from '@/lib/vertex';
import { streamLeadToBigQuery } from '@/lib/bigquery';
import { createDemoForLead, resolveDemoProvider } from '@/lib/demo-engine';
import { buildCampaignName, buildDemoPrompt, buildOutreach, buildPipeline, generateAlgorithmicKeywords } from '@/lib/pipeline';
import { applyPageSpeedAudit, runPageSpeedAudit } from '@/lib/pagespeed';
import { applyWebsiteSnapshot, inspectWebsite } from '@/lib/website';
import { scrapeAndEnrichInstagramLead } from '@/lib/instagram';
import { buildSmsOutreach } from '@/lib/sms';
import { logError, withTimeout } from '@/lib/http';
import type { AppSettings, CampaignInput, Lead } from '@/lib/types';

const AI_CALL_TIMEOUT_MS = 60_000;

export type CampaignPhase =
  | 'keywords'
  | 'discover'
  | 'audit'
  | 'score'
  | 'demos'
  | 'save'
  | 'done'
  | 'error';

export type CampaignEvent =
  | { type: 'status'; phase: CampaignPhase; message: string }
  | { type: 'keywords'; keywords: string[] }
  | { type: 'discovered'; count: number }
  | { type: 'lead'; name: string; website?: string; status: string; score?: number; index: number; total: number }
  | { type: 'scored'; qualified: number; total: number }
  | { type: 'demo'; company: string; status: 'building' | 'ready' | 'failed'; url?: string }
  | { type: 'done'; campaign: Record<string, unknown>; leads: Lead[] }
  | { type: 'error'; message: string };

export interface RunCampaignOptions {
  input: CampaignInput;
  settings: AppSettings;
  userId: string;
  baseUrl: string;
  supabase: SupabaseClient;
  emit: (event: CampaignEvent) => void;
}

/**
 * The full campaign pipeline, shared by the SSE live route and the
 * classic POST route. Emits granular progress events so the UI can show
 * real work happening instead of a frozen spinner.
 */
export async function runCampaign(opts: RunCampaignOptions): Promise<void> {
  const { input, settings, userId, baseUrl, supabase, emit } = opts;

  const aiProvider = settings.aiProvider || 'gemini';
  const isVertexActive = aiProvider === 'vertex' || process.env.VERTEX_AI_ENABLED === 'true';
  const aiModel = settings.aiModel;
  const aiApiKey =
    aiProvider === 'anthropic'
      ? settings.aiApiKey || process.env.ANTHROPIC_API_KEY
      : settings.aiApiKey || process.env.GEMINI_API_KEY;
  const aiEnabled =
    isVertexActive ||
    (Boolean(aiApiKey) &&
      (Boolean(settings.aiApiKey) || process.env.GEMINI_ENABLED === 'true' || process.env.ANTHROPIC_ENABLED === 'true'));

  const v0ApiKey = settings.v0ApiKey || process.env.V0_API_KEY;
  const demoProvider = resolveDemoProvider();
  const maxAutoDemos = Math.max(0, Math.min(input.demoLimit ?? settings.maxAutoDemosPerCampaign ?? 3, 25));
  const minDemoScore = Math.max(0, Math.min(input.demoMinScore ?? settings.minDemoScore ?? 75, 100));
  const canAutoGenerate = input.autoGenerateDemos === true && maxAutoDemos > 0 && Boolean(v0ApiKey);

  // 0. Campaign row first — nothing below can lose the record.
  const { data: campaign, error: campaignError } = await supabase
    .from('campaigns')
    .insert({
      name: buildCampaignName(input),
      audience: input.audience,
      locations: input.locations,
      source: input.source,
      demo_type: input.demoType,
      channel: input.channel,
      status: 'running',
      total_prospects: 0,
      qualified: 0,
      demos_generated: 0,
      user_id: userId
    })
    .select()
    .single();

  if (campaignError) throw new Error(campaignError.message);

  try {
    // 1. Keywords
    emit({ type: 'status', phase: 'keywords', message: 'Expanding your request into search queries…' });
    let keywords: string[] = [];
    if (aiEnabled) {
      try {
        if (isVertexActive) {
          keywords = await withTimeout(
            generateVertexCampaignKeywords(input, {
              projectId: settings.gcpProjectId || undefined,
              location: settings.gcpLocation || undefined,
              model: settings.vertexModel || settings.aiModel,
              enableGrounding: settings.vertexGrounding
            }),
            AI_CALL_TIMEOUT_MS,
            'keyword-generation'
          );
        } else if (aiProvider === 'anthropic' && aiApiKey) {
          keywords = await withTimeout(
            generateCampaignKeywordsAnthropic(input.audience, input.locations, input.source, aiApiKey, aiModel ?? undefined),
            AI_CALL_TIMEOUT_MS,
            'keyword-generation'
          );
        } else if (aiApiKey) {
          keywords = await withTimeout(
            generateCampaignKeywords(input.audience, input.locations, input.source, aiApiKey, aiModel ?? undefined),
            AI_CALL_TIMEOUT_MS,
            'keyword-generation'
          );
        }
      } catch (err) {
        logError('runner:keywords', err, { provider: aiProvider });
      }
    }
    if (keywords.length === 0) keywords = generateAlgorithmicKeywords(input);
    emit({ type: 'keywords', keywords });

    // 2. Discovery
    emit({ type: 'status', phase: 'discover', message: `Searching live sources for ${input.audience}…` });
    let prospects: Awaited<ReturnType<typeof discoverProspects>> = [];
    try {
      prospects = await discoverProspects(input, keywords);
    } catch (err) {
      logError('runner:discovery', err);
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
      throw new Error(err instanceof Error ? err.message : 'Lead discovery failed.');
    }

    const pipeline = buildPipeline(input, keywords, prospects);
    if (pipeline.leads.length === 0) {
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
      throw new Error(
        'No real leads found for that request. Try a different audience or location — or check that SERPAPI_KEY is configured for Google Maps discovery.'
      );
    }
    emit({ type: 'discovered', count: pipeline.leads.length });

    // 3. Website audit (concurrency-limited, per-lead events)
    emit({ type: 'status', phase: 'audit', message: `Auditing ${pipeline.leads.length} websites…` });
    const inspectedLeads = await mapWithConcurrency(pipeline.leads, 4, async (lead, index) => {
      let current = lead;
      const siteUrl = current.website_url;
      if (siteUrl) {
        try {
          const snapshot = await inspectWebsite(siteUrl);
          current = applyWebsiteSnapshot(current, snapshot);
          const pageSpeed = await runPageSpeedAudit(siteUrl, snapshot);
          current = applyPageSpeedAudit(current, pageSpeed);
        } catch (err) {
          logError('runner:inspect', err, { website: siteUrl });
        }
      }
      if (current.instagram_url) {
        try {
          current = await scrapeAndEnrichInstagramLead(current);
        } catch (err) {
          logError('runner:instagram', err, { lead: current.company_name });
        }
      }
      current = refreshLeadArtifacts(current, input, baseUrl);
      emit({
        type: 'lead',
        name: current.company_name,
        website: current.website_url,
        status: current.status,
        index,
        total: pipeline.leads.length
      });
      return current;
    });

    // 4. AI scoring
    emit({ type: 'status', phase: 'score', message: aiEnabled ? 'Scoring and writing outreach copy…' : 'Finalizing lead data…' });
    let scored = 0;
    const analyzedLeads = await Promise.all(
      inspectedLeads.map(async (lead) => {
        if (!aiEnabled) {
          scored += 1;
          return lead;
        }
        try {
          let ai: Partial<Lead>;
          if (isVertexActive) {
            ai = await withTimeout(
              analyzeLeadWithVertex(lead, {
                projectId: settings.gcpProjectId || undefined,
                location: settings.gcpLocation || undefined,
                model: settings.vertexModel || settings.aiModel,
                enableGrounding: settings.vertexGrounding
              }),
              AI_CALL_TIMEOUT_MS,
              'lead-analysis'
            );
          } else if (aiProvider === 'anthropic' && aiApiKey) {
            ai = await withTimeout(analyzeLeadWithAnthropic(lead, aiApiKey, aiModel ?? undefined), AI_CALL_TIMEOUT_MS, 'lead-analysis');
          } else if (aiApiKey) {
            ai = await withTimeout(analyzeLeadWithGemini(lead, aiApiKey, aiModel ?? undefined), AI_CALL_TIMEOUT_MS, 'lead-analysis');
          } else {
            return lead;
          }

          const merged = {
            ...lead,
            ...ai,
            status: typeof ai.fit_score === 'number' && ai.fit_score >= 70 ? ('qualified' as const) : lead.status,
            outreach_body:
              ai.outreach_body?.replace('{{demo_url}}', lead.demo_url || `${baseUrl}/demo/${lead.id}`) ||
              buildOutreach({
                company: lead.company_name,
                contactName: lead.contact_name,
                city: lead.city,
                weakness: ai.weakness || lead.weakness,
                demoUrl: lead.demo_url || `${baseUrl}/demo/${lead.id}`,
                channel: input.channel,
                niche: lead.niche
              })
          } satisfies Lead;
          scored += 1;
          if (scored % 5 === 0 || scored === inspectedLeads.length) {
            emit({ type: 'status', phase: 'score', message: `Scored ${scored}/${inspectedLeads.length} leads…` });
          }
          return { ...merged, demo_prompt: buildDemoPrompt(merged) } satisfies Lead;
        } catch (err) {
          logError('runner:analyze', err, { lead: lead.company_name });
          return lead;
        }
      })
    );

    const contactEnrichedLeads = analyzedLeads.map((lead) => {
      const hasContact = Boolean(lead.email?.trim()) || Boolean(lead.phone?.trim()) || Boolean(lead.linkedin_url?.trim()) || Boolean(lead.instagram_url?.trim());
      if (!hasContact) {
        return {
          ...lead,
          status: 'skipped' as const,
          qualification_reason: 'Skipped: No contact email, phone number, or social handle found to reach prospect.',
          signals: [
            ...lead.signals.filter((s) => s.label !== 'Contact status'),
            { label: 'Contact status', value: 'Missing contact info', severity: 'critical' }
          ]
        } satisfies Lead;
      }
      const fitScore = typeof lead.fit_score === 'number' ? lead.fit_score : 50;
      return { ...lead, status: fitScore >= 70 ? ('qualified' as const) : ('scraped' as const) } satisfies Lead;
    });

    const qualifiedCount = contactEnrichedLeads.filter((l) => l.fit_score >= 70).length;
    emit({ type: 'scored', qualified: qualifiedCount, total: contactEnrichedLeads.length });

    // 5. Demos (budget-capped)
    let demoProcessedLeads: Lead[] = contactEnrichedLeads;
    if (canAutoGenerate) {
      emit({ type: 'status', phase: 'demos', message: `Building demos for top leads (max ${maxAutoDemos})…` });
      let generatedCount = 0;
      demoProcessedLeads = await mapWithConcurrency(contactEnrichedLeads, 2, async (lead) => {
        if (lead.status !== 'qualified' || lead.fit_score < minDemoScore || generatedCount >= maxAutoDemos) return lead;
        generatedCount += 1;
        emit({ type: 'demo', company: lead.company_name, status: 'building' });
        try {
          const demo = await withTimeout(
            createDemoForLead(lead, { settings, quality: input.demoQuality, provider: demoProvider, baseUrl }),
            180_000,
            'auto-demo'
          );
          if (demo.status === 'ready' && demo.demoUrl) {
            emit({ type: 'demo', company: lead.company_name, status: 'ready', url: demo.demoUrl });
            const updated: Lead = {
              ...lead,
              status: 'demo_ready',
              demo_url: demo.demoUrl,
              demo_provider: demo.provider || demoProvider,
              demo_quality: input.demoQuality || 'low',
              demo_prompt: demo.demoArtifact || lead.demo_prompt,
              v0_chat_id: demo.chatId,
              v0_version_id: demo.versionId
            };
            return refreshLeadArtifacts(updated, input, baseUrl);
          }
          emit({ type: 'demo', company: lead.company_name, status: 'failed' });
        } catch (err) {
          logError('runner:auto-demo', err, { lead: lead.company_name });
          emit({ type: 'demo', company: lead.company_name, status: 'failed' });
        }
        return lead;
      });
    }

    // 6. Persist
    emit({ type: 'status', phase: 'save', message: 'Saving campaign and leads…' });
    pipeline.leads = demoProcessedLeads;

    const leadsToSave = demoProcessedLeads.map((lead) => ({
      id: crypto.randomUUID(),
      user_id: userId,
      campaign_id: campaign.id,
      company_name: lead.company_name,
      contact_name: lead.contact_name,
      niche: lead.niche,
      source: lead.source,
      website_url: lead.website_url,
      linkedin_url: lead.linkedin_url,
      instagram_url: lead.instagram_url,
      city: lead.city,
      email: lead.email,
      phone: lead.phone,
      address: lead.address,
      rating: lead.rating,
      reviews_count: lead.reviews_count,
      source_url: lead.source_url,
      status: lead.status,
      fit_score: lead.fit_score,
      weakness: lead.weakness,
      qualification_reason: lead.qualification_reason,
      signals: lead.signals,
      demo_type: lead.demo_type,
      demo_quality: lead.demo_quality || input.demoQuality || 'low',
      demo_prompt: lead.demo_prompt,
      demo_url: lead.demo_url,
      demo_provider: lead.demo_provider || demoProvider,
      v0_chat_id: lead.v0_chat_id,
      v0_version_id: lead.v0_version_id,
      outreach_subject: lead.outreach_subject,
      outreach_body: lead.outreach_body,
      outreach_sms: lead.outreach_sms,
      matched_keyword: lead.matched_keyword
    }));

    let { data: savedLeads, error: leadsError } = await supabase.from('leads').insert(leadsToSave).select();
    if (leadsError && isMissingExtendedLeadColumn(leadsError.message)) {
      const legacyLeadsToSave = leadsToSave.map(
        ({ phone, address, rating, reviews_count, source_url, matched_keyword, instagram_url, demo_quality, demo_provider, outreach_sms, user_id, ...legacyLead }) => legacyLead
      );
      const legacyResult = await supabase.from('leads').insert(legacyLeadsToSave).select();
      savedLeads = legacyResult.data;
      leadsError = legacyResult.error;
    }
    if (leadsError) {
      logError('runner:save-leads', leadsError);
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
      throw new Error(`Leads could not be saved: ${leadsError.message}`);
    }

    const finalCampaign = {
      ...campaign,
      status: 'complete',
      total_prospects: demoProcessedLeads.length,
      qualified: demoProcessedLeads.filter((l) => l.fit_score >= 70).length,
      demos_generated: demoProcessedLeads.filter((l) => l.status === 'demo_ready').length,
      keywords
    };

    await supabase
      .from('campaigns')
      .update({
        status: 'complete',
        total_prospects: finalCampaign.total_prospects,
        qualified: finalCampaign.qualified,
        demos_generated: finalCampaign.demos_generated
      })
      .eq('id', campaign.id);

    if (settings.bigqueryEnabled !== false && process.env.BIGQUERY_ENABLED !== 'false') {
      Promise.allSettled((savedLeads || []).map((l) => streamLeadToBigQuery(l as unknown as Lead))).catch(() => {});
    }

    emit({
      type: 'done',
      campaign: finalCampaign as unknown as Record<string, unknown>,
      leads: mergeSavedLeadIds(savedLeads || [], demoProcessedLeads)
    });
  } catch (err) {
    logError('runner:fatal', err, { campaignId: campaign.id });
    try {
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
    } catch {
      // best-effort status update
    }
    throw err;
  }
}

function refreshLeadArtifacts(lead: Lead, input: CampaignInput, baseUrl: string): Lead {
  const demoUrl = lead.demo_url || `${baseUrl}/demo/${lead.id}`;
  const quality = lead.demo_quality || input.demoQuality || 'low';
  return {
    ...lead,
    demo_quality: quality,
    demo_prompt: buildDemoPrompt(lead, quality),
    outreach_body: buildOutreach({
      company: lead.company_name,
      contactName: lead.contact_name,
      city: lead.city,
      weakness: lead.weakness,
      demoUrl,
      channel: input.channel,
      niche: lead.niche
    }),
    outreach_sms: buildSmsOutreach(lead)
  };
}

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  mapper: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = [];
  let nextIndex = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (nextIndex < items.length) {
      const currentIndex = nextIndex;
      nextIndex += 1;
      results[currentIndex] = await mapper(items[currentIndex], currentIndex);
    }
  });
  await Promise.all(workers);
  return results;
}

function isMissingExtendedLeadColumn(message: string) {
  return /schema cache|column/i.test(message) && /(phone|address|rating|reviews_count|source_url|matched_keyword|instagram_url|demo_provider|outreach_sms)/i.test(message);
}

function mergeSavedLeadIds(savedLeads: Lead[], analyzedLeads: Lead[]): Lead[] {
  if (!savedLeads.length) return analyzedLeads;
  const savedById = new Map(savedLeads.map((lead) => [lead.id, lead]));
  return analyzedLeads.map((lead) => {
    const saved = savedById.get(lead.id);
    if (!saved) return lead;
    return { ...lead, id: saved.id, campaign_id: saved.campaign_id, created_at: saved.created_at };
  });
}
