import type { CampaignInput, DemoType, LeadSource, OutreachChannel } from '@/lib/types';
import { fetchWithTimeout } from '@/lib/http';
import type { AppSettings } from '@/lib/types';

/**
 * Turns a plain-language request ("dentists in the uk, 25 leads, sms")
 * into a structured CampaignInput. Tries the configured AI provider first
 * and always falls back to a deterministic heuristic parser, so the simple
 * composer works even with zero AI keys configured.
 */

export interface ParsedCampaignRequest {
  audience: string;
  locations: string;
  source: LeadSource;
  channel: OutreachChannel;
  demoType: DemoType;
  limit: number;
  parsedBy: 'ai' | 'heuristic';
}

const LOCATION_ALIASES: Record<string, string> = {
  uk: 'United Kingdom',
  britain: 'United Kingdom',
  england: 'United Kingdom',
  usa: 'United States',
  us: 'United States',
  america: 'United States',
  uae: 'United Arab Emirates',
  nyc: 'New York, NY',
  'new york': 'New York, NY'
};

export function normalizeParsed(parsed: ParsedCampaignRequest): CampaignInput {
  return {
    audience: parsed.audience.slice(0, 300) || 'local service businesses',
    locations: parsed.locations.slice(0, 500),
    source: parsed.source,
    sourcePayload: '',
    demoType: parsed.demoType,
    channel: parsed.channel,
    limit: Math.min(Math.max(Number(parsed.limit) || 25, 1), 100),
    autoGenerateDemos: true, // simple flow always offers demos, budget-capped
    demoQuality: 'low',
    demoProvider: 'v0',
    demoLimit: 3,
    demoMinScore: 75
  };
}

export async function parseCampaignRequest(
  request: string,
  settings: AppSettings,
  limitOverride?: number
): Promise<ParsedCampaignRequest> {
  const heuristic = parseHeuristically(request, limitOverride);

  const apiKey = settings.aiApiKey || process.env.GEMINI_API_KEY;
  const model = settings.aiModel || process.env.GEMINI_MODEL || 'gemini-2.5-flash';
  if (!apiKey || !request.trim()) return heuristic;

  try {
    const prompt = `Parse this campaign request from a non-technical user into JSON. Request: "${request.slice(0, 400)}"

Return ONLY JSON:
{"audience":"<who to contact, 2-6 words, e.g. 'dentists' or 'B2B SaaS startups'>","locations":"<comma-separated city/region names, empty if none>","channel":"email|sms|multi|linkedin","limit":<number 1-100>,"source":"google_maps|instagram|url_list|csv"}

Rules:
- audience: the business type/people to reach. Strip filler like "high-ticket", "find me", "leads for".
- locations: expand abbreviations (uk -> United Kingdom). Empty string if not mentioned.
- channel: only if explicitly mentioned (sms, text, linkedin, email+sms -> multi). Default email.
- limit: only if mentioned. Default 25.
- source: instagram only if Instagram mentioned; csv/url_list only if data pasted (it won't be here). Default google_maps.`;

    const res = await fetchWithTimeout(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-goog-api-key': apiKey },
        body: JSON.stringify({
          contents: [{ role: 'user', parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.1, responseMimeType: 'application/json' }
        })
      },
      15_000
    );

    if (!res.ok) return heuristic;
    const payload = (await res.json()) as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
    const text = payload.candidates?.[0]?.content?.parts?.[0]?.text || '';
    const start = text.indexOf('{');
    const end = text.lastIndexOf('}');
    if (start === -1 || end <= start) return heuristic;
    const raw = JSON.parse(text.slice(start, end + 1)) as Record<string, unknown>;

    const audience = typeof raw.audience === 'string' && raw.audience.trim() ? raw.audience.trim() : heuristic.audience;
    const locations = typeof raw.locations === 'string' ? raw.locations.trim() : heuristic.locations;
    const channel = isChannel(raw.channel) ? raw.channel : heuristic.channel;
    const source = isSource(raw.source) ? raw.source : heuristic.source;
    const aiLimit = Number(raw.limit);

    return {
      audience,
      locations,
      source,
      channel,
      demoType: 'website',
      limit: limitOverride ?? (Number.isFinite(aiLimit) ? Math.min(Math.max(aiLimit, 1), 100) : heuristic.limit),
      parsedBy: 'ai'
    };
  } catch {
    return heuristic;
  }
}

function isChannel(v: unknown): v is OutreachChannel {
  return v === 'email' || v === 'sms' || v === 'multi' || v === 'linkedin';
}

function isSource(v: unknown): v is LeadSource {
  return v === 'google_maps' || v === 'instagram' || v === 'url_list' || v === 'csv' || v === 'linkedin' || v === 'product_hunt' || v === 'apollo';
}

/**
 * Deterministic fallback parser — no AI needed.
 * "dentists in the uk, 50 leads, sms" -> audience "dentists", locations
 * "United Kingdom", limit 50, channel sms.
 */
export function parseHeuristically(request: string, limitOverride?: number): ParsedCampaignRequest {
  let text = ` ${request.trim()} `;

  // channel
  let channel: OutreachChannel = 'email';
  if (/\b(email\s*\+\s*sms|email and sms|multi)\b/i.test(text)) channel = 'multi';
  else if (/\b(sms|text message|texting)\b/i.test(text)) channel = 'sms';
  else if (/\blinkedin\b/i.test(text)) channel = 'linkedin';

  // limit
  let limit = 25;
  const limitMatch = text.match(/(\d{1,3})\s*(leads?|prospects?|businesses|results|companies|clinics|shops|restaurants)/i);
  if (limitMatch) limit = Number(limitMatch[1]);
  if (limitOverride) limit = limitOverride;

  // locations: "in X", "from X", "across X"
  const locations: string[] = [];
  const inMatch = text.matchAll(/\b(?:in|from|across|around)\s+([A-Za-z][A-Za-z\s,\.]{2,40}?)(?=[,;]|\s+\d|\s+(?:leads?|prospects?|businesses|with|and|who|using|via)\b|$)/gi);
  for (const m of inMatch) {
    const raw = m[1].trim().replace(/[,\.\s]+$/, '');
    if (!raw) continue;
    const alias = LOCATION_ALIASES[raw.toLowerCase()];
    locations.push(alias || titleCaseLocation(raw));
    text = text.replace(m[0], ' ');
  }

  // source
  let source: LeadSource = 'google_maps';
  if (/\binstagram\b/i.test(request)) source = 'instagram';
  else if (/\bcsv\b/i.test(request)) source = 'csv';
  else if (/\b(urls?|links?)\b/i.test(request)) source = 'url_list';

  // audience: strip command filler + channel/limit words, keep the rest
  const audience = text
    .replace(/\b(find|find me|get|get me|scrape|scrape me|start|launch|run|create|build|make|target|reach|contact|outreach|campaign|leads?|prospects?|businesses|companies|results|for me|please)\b/gi, ' ')
    .replace(/\b(email|sms|linkedin|multi)\b/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  return {
    audience: audience || 'local service businesses',
    locations: locations.join('; '),
    source,
    channel,
    demoType: 'website',
    limit: Math.min(Math.max(limit, 1), 100),
    parsedBy: 'heuristic'
  };
}

function titleCaseLocation(value: string): string {
  return value
    .split(/\s+/)
    .map((word) => (word.length > 2 ? word[0].toUpperCase() + word.slice(1) : word.toUpperCase()))
    .join(' ');
}
