export type LeadSource = 'google_maps' | 'instagram' | 'linkedin' | 'product_hunt' | 'apollo' | 'csv' | 'url_list';

export type LeadStatus =
  | 'new'
  | 'scraped'
  | 'qualified'
  | 'skipped'
  | 'demo_ready'
  | 'demo_failed'
  | 'outreach_sent'
  | 'replied'
  | 'converted';

export type DemoType = 'website' | 'landing_page' | 'app_mockup';

export type DemoQuality = 'low' | 'high';

export type OutreachChannel = 'email' | 'sms' | 'multi' | 'linkedin';

export type DemoProvider = 'v0' | 'agentic' | 'hybrid';

export interface CampaignInput {
  audience: string;
  locations: string;
  source: LeadSource;
  sourcePayload: string;
  demoType: DemoType;
  channel: OutreachChannel;
  limit: number;
  keywords?: string[];
  autoGenerateDemos?: boolean;
  demoQuality?: DemoQuality;
  demoProvider?: DemoProvider;
  demoLimit?: number;
  demoMinScore?: number;
}

export interface DigitalSignal {
  label: string;
  value: string;
  severity: 'positive' | 'warning' | 'critical';
}

export interface OutreachEvent {
  id: string;
  lead_id: string;
  event_type: 'sent' | 'opened' | 'clicked' | 'replied';
  channel?: string;
  created_at: string;
  event_data?: Record<string, unknown>;
}

export interface Lead {
  id: string;
  user_id?: string;
  campaign_id?: string;
  company_name: string;
  contact_name?: string;
  niche: string;
  source: LeadSource;
  website_url?: string;
  linkedin_url?: string;
  instagram_url?: string;
  city?: string;
  email?: string;
  phone?: string;
  address?: string;
  rating?: number;
  reviews_count?: number;
  source_url?: string;
  status: LeadStatus;
  fit_score: number;
  weakness: string;
  qualification_reason: string;
  signals: DigitalSignal[];
  demo_type: DemoType;
  demo_quality?: DemoQuality;
  demo_prompt: string;
  demo_url?: string;
  demo_provider?: DemoProvider;
  v0_chat_id?: string;
  v0_version_id?: string;
  outreach_subject: string;
  outreach_body: string;
  outreach_sms?: string;
  matched_keyword?: string;
  opens: number;
  clicks: number;
  replies: number;
  created_at: string;
}

export interface Campaign {
  id: string;
  user_id?: string;
  name: string;
  audience: string;
  locations?: string;
  source: LeadSource;
  demo_type: DemoType;
  channel: OutreachChannel;
  status: 'draft' | 'running' | 'paused' | 'complete';
  total_prospects: number;
  qualified: number;
  demos_generated: number;
  outreach_sent: number;
  replies: number;
  conversions: number;
  keywords?: string[];
  created_at: string;
}

export interface PipelineResult {
  campaign: Campaign;
  leads: Lead[];
}

export interface PricingPackage {
  name: string;
  price: string;
  duration: string;
  popular?: boolean;
  description: string;
  perks: string[];
}

export interface CalculatorOption {
  label: string;
  price: number;
}

export interface CalculatorConfig {
  serviceType: string;
  unitLabel: string;
  basePrice: number;
  pricePerUnit: number;
  defaultUnits: number;
  minUnits: number;
  maxUnits: number;
  step: number;
  options: CalculatorOption[];
}

export interface DemoReview {
  author: string;
  location?: string;
  content: string;
  rating: number;
  verified?: boolean;
}

export interface DemoFaq {
  question: string;
  answer: string;
}

export interface AgenticStrategy {
  title: string;
  tagline?: string;
  positioning: string;
  heroHeadline: string;
  primaryCta: string;
  secondaryCta?: string;
  sections: Array<{ title: string; purpose: string; copy: string }>;
  proofPoints: string[];
  pricingPackages?: PricingPackage[];
  calculator?: CalculatorConfig;
  comparison?: { current: string[]; modernized: string[] };
  reviews?: DemoReview[];
  faqs?: DemoFaq[];
  promptEnhancement?: string;
}

export interface V0DemoResult {
  chatId?: string;
  versionId?: string;
  demoUrl?: string;
  deploymentUrl?: string;
  webUrl?: string;
  provider?: DemoProvider;
  status?: 'ready' | 'failed';
  error?: string;
  demoArtifact?: string;
}

export interface AppSettings {
  aiProvider: 'vertex' | 'gemini' | 'anthropic';
  aiModel: string;
  aiApiKey: string;
  gcpProjectId?: string;
  gcpLocation?: string;
  gcpClientEmail?: string;
  vertexModel?: string;
  vertexGrounding?: boolean;
  bigqueryEnabled?: boolean;
  bigqueryDataset?: string;
  v0ApiKey: string;
  v0Model: string;
  demoProvider?: DemoProvider;
  defaultDemoQuality?: DemoQuality;
  maxAutoDemosPerCampaign?: number;
  minDemoScore?: number;
  resendApiKey?: string;
  fromEmail?: string;
  fromName?: string;
  twilioAccountSid?: string;
  twilioAuthToken?: string;
  twilioPhoneNumber?: string;
  brandName?: string;
  customInstructions?: string;
}
