import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/api-auth';
import { checkRateLimit, rateLimitResponse } from '@/lib/rate-limit';
import { getUserSettings } from '@/lib/settings';
import { runCampaign } from '@/lib/campaign-runner';
import { logError } from '@/lib/http';
import type { CampaignInput } from '@/lib/types';

export const maxDuration = 300;

export async function GET() {
  const auth = await requireUser();
  if (!auth.ok) return auth.response;

  const { data: campaigns, error: campaignError } = await auth.supabase
    .from('campaigns')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(20);
  if (campaignError) {
    logError('GET /api/campaigns', campaignError);
    return NextResponse.json({ error: campaignError.message }, { status: 500 });
  }

  const campaignIds = (campaigns || []).map((campaign) => campaign.id);
  const { data: leads, error: leadsError } = campaignIds.length
    ? await auth.supabase
        .from('leads')
        .select('*')
        .in('campaign_id', campaignIds)
        .order('created_at', { ascending: false })
    : { data: [], error: null };
  if (leadsError) {
    logError('GET /api/campaigns:leads', leadsError);
    return NextResponse.json({ error: leadsError.message }, { status: 500 });
  }

  return NextResponse.json({ campaigns, leads, persistence: 'supabase' });
}

/**
 * Classic JSON campaign creation. Shares the exact pipeline with the live
 * SSE route (lib/campaign-runner) — this wrapper just buffers the events
 * and returns the final payload.
 */
export async function POST(req: Request) {
  const auth = await requireUser();
  if (!auth.ok) return auth.response;

  const rl = checkRateLimit(req, 'campaigns_post', 10, 60_000);
  if (!rl.ok) return rateLimitResponse(rl.retryAfterSec);

  let body: Partial<CampaignInput>;
  try {
    body = (await req.json()) as Partial<CampaignInput>;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  // Credentials resolve server-side from stored settings + env.
  const settings = await getUserSettings(auth.user.id);

  const input = normalizeCampaignInput(body);
  const baseUrl = getBaseUrl(req);

  let finalPayload: { campaign: Record<string, unknown>; leads: CampaignInput[] | unknown[] } | null = null;

  try {
    await runCampaign({
      input,
      settings,
      userId: auth.user.id,
      baseUrl,
      supabase: auth.supabase,
      emit: (event) => {
        if (event.type === 'done') {
          finalPayload = { campaign: event.campaign, leads: event.leads };
        }
      }
    });

    if (!finalPayload) {
      return NextResponse.json({ error: 'Campaign ended without a result.' }, { status: 500 });
    }

    return NextResponse.json({
      campaign: (finalPayload as { campaign: Record<string, unknown> }).campaign,
      leads: (finalPayload as { leads: unknown[] }).leads,
      persistence: 'supabase'
    });
  } catch (err) {
    logError('POST /api/campaigns', err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Campaign processing failed.' },
      { status: err instanceof Error && err.message.includes('No real leads') ? 400 : 502 }
    );
  }
}

function normalizeCampaignInput(body: Partial<CampaignInput>): CampaignInput {
  return {
    audience: (body.audience?.trim() || 'High-ticket local service businesses').slice(0, 300),
    locations: (body.locations?.trim() || '').slice(0, 500),
    source: body.source || 'google_maps',
    sourcePayload: (body.sourcePayload || '').slice(0, 100_000),
    demoType: body.demoType || 'website',
    channel: body.channel || 'email',
    limit: Math.min(Math.max(Number(body.limit || 25), 1), 100),
    autoGenerateDemos: body.autoGenerateDemos === true,
    demoQuality: body.demoQuality === 'high' ? 'high' : 'low',
    demoProvider: 'v0',
    demoLimit: body.demoLimit === undefined ? undefined : Math.min(Math.max(Number(body.demoLimit), 0), 25),
    demoMinScore: body.demoMinScore === undefined ? undefined : Math.min(Math.max(Number(body.demoMinScore), 0), 100)
  };
}

function getBaseUrl(req: Request) {
  const requestOrigin = new URL(req.url).origin;
  const configured = process.env.APP_BASE_URL;
  if (!configured || configured.includes('localhost')) return requestOrigin;
  return configured;
}
