import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/api-auth';
import { checkRateLimit, rateLimitResponse } from '@/lib/rate-limit';
import { generateCampaignKeywordsAnthropic, analyzeLeadWithAnthropic } from '@/lib/anthropic';
import { discoverProspects } from '@/lib/discovery';
import { analyzeLeadWithGemini, generateCampaignKeywords } from '@/lib/gemini';
import { generateVertexCampaignKeywords, analyzeLeadWithVertex } from '@/lib/vertex';
import { streamLeadToBigQuery } from '@/lib/bigquery';
import { createDemoForLead, resolveDemoProvider } from '@/lib/demo-engine';
import { buildCampaignName, buildDemoPrompt, buildOutreach, buildPipeline, generateAlgorithmicKeywords } from '@/lib/pipeline';
import { applyPageSpeedAudit, runPageSpeedAudit } from '@/lib/pagespeed';
import { applyWebsiteSnapshot, inspectWebsite } from '@/lib/website';
import { scrapeAndEnrichInstagramLead } from '@/lib/instagram';
import { buildSmsOutreach } from '@/lib/sms';
import { getUserSettings } from '@/lib/settings';
import { logError, withTimeout } from '@/lib/http';
import type { AppSettings, CampaignInput, Lead } from '@/lib/types';

const AI_CALL_TIMEOUT_MS = 60_000;

export async function GET() {
  const auth = await requireUser();
  if (!auth.ok) return auth.response;

  const { data: campaigns, error: campaignError } = await auth.supabase
    .from('campaigns')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(20);
  if (campaignError) {
    logError('GET /api/campaigns', campaignError);
    return NextResponse.json({ error: campaignError.message }, { status: 500 });
  }

  const campaignIds = (campaigns || []).map((campaign) => campaign.id);
  const { data: leads, error: leadsError } = campaignIds.length
    ? await auth.supabase
        .from('leads')
        .select('*')
        .in('campaign_id', campaignIds)
        .order('created_at', { ascending: false })
    : { data: [], error: null };
  if (leadsError) {
    logError('GET /api/campaigns:leads', leadsError);
    return NextResponse.json({ error: leadsError.message }, { status: 500 });
  }

  return NextResponse.json({ campaigns, leads, persistence: 'supabase' });
}

export async function POST(req: Request) {
  const auth = await requireUser();
  if (!auth.ok) return auth.response;

  const rl = checkRateLimit(req, 'campaigns_post', 10, 60_000);
  if (!rl.ok) return rateLimitResponse(rl.retryAfterSec);

  const userId = auth.user.id;
  const supabase = auth.supabase;
  const baseUrl = getBaseUrl(req);

  let body: Partial<CampaignInput>;
  try {
    body = (await req.json()) as Partial<CampaignInput>;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body.' }, { status: 400 });
  }

  // NOTE: credentials are resolved server-side from the user's stored
  // settings + env. Anything under body.settings is intentionally ignored.
  const settings = await getUserSettings(userId);

  const input = normalizeCampaignInput(body);

  const aiProvider = settings.aiProvider || 'gemini';
  const isVertexActive = aiProvider === 'vertex' || process.env.VERTEX_AI_ENABLED === 'true';
  const aiApiKey =
    aiProvider === 'anthropic'
      ? settings.aiApiKey || process.env.ANTHROPIC_API_KEY
      : settings.aiApiKey || process.env.GEMINI_API_KEY;
  const aiModel = settings.aiModel;
  const aiEnabled =
    isVertexActive ||
    (Boolean(aiApiKey) &&
      (Boolean(settings.aiApiKey) || process.env.GEMINI_ENABLED === 'true' || process.env.ANTHROPIC_ENABLED === 'true'));

  const v0ApiKey = settings.v0ApiKey || process.env.V0_API_KEY;
  const demoProvider = resolveDemoProvider();
  const autoGenerateDemos = input.autoGenerateDemos === true;
  const maxAutoDemos = Math.max(0, Math.min(input.demoLimit ?? settings.maxAutoDemosPerCampaign ?? 3, 25));
  const minDemoScore = Math.max(0, Math.min(input.demoMinScore ?? settings.minDemoScore ?? 75, 100));
  const canAutoGenerate = autoGenerateDemos && maxAutoDemos > 0 && Boolean(v0ApiKey);

  // 0. Persist the campaign row up-front so the record survives timeouts or
  //    partial failures mid-pipeline (counters are refreshed at the end).
  const { data: campaign, error: campaignError } = await supabase
    .from('campaigns')
    .insert({
      name: buildCampaignName(input),
      audience: input.audience,
      locations: input.locations,
      source: input.source,
      demo_type: input.demoType,
      channel: input.channel,
      status: 'running',
      total_prospects: 0,
      qualified: 0,
      demos_generated: 0,
      user_id: userId
    })
    .select()
    .single();

  if (campaignError) {
    logError('POST /api/campaigns:insert', campaignError);
    return NextResponse.json({ error: campaignError.message }, { status: 500 });
  }

  try {
    // 1. Generate multi-keyword search queries (Vertex AI, Gemini, or Anthropic)
    let keywords: string[] = [];
    if (aiEnabled) {
      try {
        if (isVertexActive) {
          keywords = await withTimeout(
            generateVertexCampaignKeywords(input, {
              projectId: settings.gcpProjectId || undefined,
              location: settings.gcpLocation || undefined,
              model: settings.vertexModel || settings.aiModel,
              enableGrounding: settings.vertexGrounding
            }),
            AI_CALL_TIMEOUT_MS,
            'keyword-generation'
          );
        } else if (aiProvider === 'anthropic' && aiApiKey) {
          keywords = await withTimeout(
            generateCampaignKeywordsAnthropic(input.audience, input.locations, input.source, aiApiKey, aiModel),
            AI_CALL_TIMEOUT_MS,
            'keyword-generation'
          );
        } else if (aiApiKey) {
          keywords = await withTimeout(
            generateCampaignKeywords(input.audience, input.locations, input.source, aiApiKey, aiModel),
            AI_CALL_TIMEOUT_MS,
            'keyword-generation'
          );
        }
      } catch (err) {
        logError('campaigns:keywords', err, { provider: aiProvider });
        keywords = [];
      }
    }
    if (keywords.length === 0) {
      keywords = generateAlgorithmicKeywords(input);
    }

    // 2. Discover prospects
    let discoveredProspects: Awaited<ReturnType<typeof discoverProspects>> = [];
    try {
      discoveredProspects = await discoverProspects(input, keywords);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Lead discovery failed.';
      logError('campaigns:discovery', err);
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
      return NextResponse.json({ error: message, campaignId: campaign.id }, { status: 502 });
    }

    const pipeline = buildPipeline(input, keywords, discoveredProspects);
    if (pipeline.leads.length === 0) {
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
      return NextResponse.json(
        {
          error:
            'No real leads found. Paste CSV/URL rows, use Google Maps with SERPAPI_KEY, or configure APIFY_ACTOR_ID/APIFY_TASK_ID for this source.',
          campaignId: campaign.id
        },
        { status: 400 }
      );
    }

    // 3. Website inspection + PageSpeed audit (concurrency-limited)
    const inspectedLeads = await mapWithConcurrency(pipeline.leads, 4, async (lead) => {
      let current = lead;

      const siteUrl = current.website_url;
      if (siteUrl) {
        try {
          const snapshot = await inspectWebsite(siteUrl);
          current = applyWebsiteSnapshot(current, snapshot);
          const pageSpeed = await runPageSpeedAudit(siteUrl, snapshot);
          current = applyPageSpeedAudit(current, pageSpeed);
        } catch (err) {
          logError('campaigns:inspect', err, { website: siteUrl });
        }
      }

      if (current.instagram_url) {
        try {
          current = await scrapeAndEnrichInstagramLead(current);
        } catch (err) {
          logError('campaigns:instagram', err, { lead: current.company_name });
        }
      }

      return refreshLeadArtifacts(current, input, baseUrl);
    });

    // 4. AI scoring & outreach copy per lead
    const analyzedLeads = await Promise.all(
      inspectedLeads.map(async (lead) => {
        if (!aiEnabled) return lead;
        try {
          let ai: Partial<Lead>;
          if (isVertexActive) {
            ai = await withTimeout(
              analyzeLeadWithVertex(lead, {
                projectId: settings.gcpProjectId || undefined,
                location: settings.gcpLocation || undefined,
                model: settings.vertexModel || settings.aiModel,
                enableGrounding: settings.vertexGrounding
              }),
              AI_CALL_TIMEOUT_MS,
              'lead-analysis'
            );
          } else if (aiProvider === 'anthropic' && aiApiKey) {
            ai = await withTimeout(analyzeLeadWithAnthropic(lead, aiApiKey, aiModel), AI_CALL_TIMEOUT_MS, 'lead-analysis');
          } else if (aiApiKey) {
            ai = await withTimeout(analyzeLeadWithGemini(lead, aiApiKey, aiModel), AI_CALL_TIMEOUT_MS, 'lead-analysis');
          } else {
            return lead;
          }

          const merged = {
            ...lead,
            ...ai,
            status: typeof ai.fit_score === 'number' && ai.fit_score >= 70 ? ('qualified' as const) : lead.status,
            outreach_body:
              ai.outreach_body?.replace('{{demo_url}}', lead.demo_url || `${baseUrl}/demo/${lead.id}`) ||
              buildOutreach({
                company: lead.company_name,
                contactName: lead.contact_name,
                city: lead.city,
                weakness: ai.weakness || lead.weakness,
                demoUrl: lead.demo_url || `${baseUrl}/demo/${lead.id}`,
                channel: input.channel,
                niche: lead.niche
              })
          } satisfies Lead;
          return {
            ...merged,
            demo_prompt: buildDemoPrompt(merged)
          } satisfies Lead;
        } catch (err) {
          logError('campaigns:analyze', err, { lead: lead.company_name });
          return lead;
        }
      })
    );

    const contactEnrichedLeads = analyzedLeads.map((lead) => {
      const hasContact = Boolean(lead.email?.trim()) || Boolean(lead.phone?.trim()) || Boolean(lead.linkedin_url?.trim()) || Boolean(lead.instagram_url?.trim());

      if (!hasContact) {
        return {
          ...lead,
          status: 'skipped' as const,
          qualification_reason: 'Skipped: No contact email, phone number, or social handle found to reach prospect.',
          signals: [
            ...lead.signals.filter((s) => s.label !== 'Contact status'),
            { label: 'Contact status', value: 'Missing contact info', severity: 'critical' }
          ]
        } satisfies Lead;
      }

      const fitScore = typeof lead.fit_score === 'number' ? lead.fit_score : 50;
      const finalStatus = fitScore >= 70 ? ('qualified' as const) : ('scraped' as const);

      return {
        ...lead,
        status: finalStatus
      } satisfies Lead;
    });

    // 5. Auto-generate demos inside credit guardrails
    let demoProcessedLeads: Lead[] = contactEnrichedLeads;
    if (canAutoGenerate) {
      let generatedCount = 0;
      demoProcessedLeads = await mapWithConcurrency(contactEnrichedLeads, 2, async (lead) => {
        if (lead.status !== 'qualified' || lead.fit_score < minDemoScore || generatedCount >= maxAutoDemos) return lead;
        generatedCount += 1;
        try {
          const demo = await withTimeout(
            createDemoForLead(lead, {
              settings,
              quality: input.demoQuality,
              provider: demoProvider,
              baseUrl
            }),
            180_000,
            'auto-demo'
          );
          if (demo.status === 'ready' && demo.demoUrl) {
            const updated: Lead = {
              ...lead,
              status: 'demo_ready',
              demo_url: demo.demoUrl,
              demo_provider: demo.provider || demoProvider,
              demo_quality: input.demoQuality || 'low',
              demo_prompt: demo.demoArtifact || lead.demo_prompt,
              v0_chat_id: demo.chatId,
              v0_version_id: demo.versionId
            };
            return refreshLeadArtifacts(updated, input, baseUrl);
          }
        } catch (err) {
          logError('campaigns:auto-demo', err, { lead: lead.company_name });
        }
        return lead;
      });
    }

    // 6. Persist leads owned by this user
    pipeline.leads = demoProcessedLeads;
    pipeline.campaign.qualified = demoProcessedLeads.filter((lead) => lead.fit_score >= 70).length;
    pipeline.campaign.demos_generated = demoProcessedLeads.filter((lead) => lead.status === 'demo_ready').length;

    const leadsToSave = demoProcessedLeads.map((lead) => ({
      id: crypto.randomUUID(),
      user_id: userId,
      campaign_id: campaign.id,
      company_name: lead.company_name,
      contact_name: lead.contact_name,
      niche: lead.niche,
      source: lead.source,
      website_url: lead.website_url,
      linkedin_url: lead.linkedin_url,
      instagram_url: lead.instagram_url,
      city: lead.city,
      email: lead.email,
      phone: lead.phone,
      address: lead.address,
      rating: lead.rating,
      reviews_count: lead.reviews_count,
      source_url: lead.source_url,
      status: lead.status,
      fit_score: lead.fit_score,
      weakness: lead.weakness,
      qualification_reason: lead.qualification_reason,
      signals: lead.signals,
      demo_type: lead.demo_type,
      demo_quality: lead.demo_quality || input.demoQuality || 'low',
      demo_prompt: lead.demo_prompt,
      demo_url: lead.demo_url,
      demo_provider: lead.demo_provider || demoProvider,
      v0_chat_id: lead.v0_chat_id,
      v0_version_id: lead.v0_version_id,
      outreach_subject: lead.outreach_subject,
      outreach_body: lead.outreach_body,
      outreach_sms: lead.outreach_sms,
      matched_keyword: lead.matched_keyword
    }));

    let { data: savedLeads, error: leadsError } = await supabase.from('leads').insert(leadsToSave).select();
    if (leadsError && isMissingExtendedLeadColumn(leadsError.message)) {
      const legacyLeadsToSave = leadsToSave.map(
        ({ phone, address, rating, reviews_count, source_url, matched_keyword, instagram_url, demo_quality, demo_provider, outreach_sms, user_id, ...legacyLead }) => legacyLead
      );
      const legacyResult = await supabase.from('leads').insert(legacyLeadsToSave).select();
      savedLeads = legacyResult.data;
      leadsError = legacyResult.error;
    }
    if (leadsError) {
      logError('campaigns:save-leads', leadsError);
      // Campaign row already exists; report the partial failure honestly.
      await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
      return NextResponse.json({ error: `Leads could not be saved: ${leadsError.message}`, campaignId: campaign.id }, { status: 500 });
    }

    // 7. Refresh counters to final state and mark complete
    await supabase
      .from('campaigns')
      .update({
        status: 'complete',
        total_prospects: demoProcessedLeads.length,
        qualified: pipeline.campaign.qualified,
        demos_generated: pipeline.campaign.demos_generated
      })
      .eq('id', campaign.id);

    // 8. Non-blocking analytics stream
    if (shouldStreamToBigQuery(settings)) {
      Promise.allSettled(
        (savedLeads || []).map((l) => streamLeadToBigQuery(l as unknown as Lead))
      ).catch(() => {});
    }

    return NextResponse.json({
      campaign: {
        ...campaign,
        status: 'complete',
        total_prospects: demoProcessedLeads.length,
        qualified: pipeline.campaign.qualified,
        demos_generated: pipeline.campaign.demos_generated,
        keywords
      },
      leads: mergeSavedLeadIds(savedLeads || [], demoProcessedLeads),
      persistence: 'supabase'
    });
  } catch (err) {
    logError('POST /api/campaigns:fatal', err, { campaignId: campaign.id });
    await supabase.from('campaigns').update({ status: 'draft' }).eq('id', campaign.id);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Campaign processing failed.', campaignId: campaign.id },
      { status: 500 }
    );
  }
}

function refreshLeadArtifacts(lead: Lead, input: CampaignInput, baseUrl: string): Lead {
  const demoUrl = lead.demo_url || `${baseUrl}/demo/${lead.id}`;
  const quality = lead.demo_quality || input.demoQuality || 'low';
  return {
    ...lead,
    demo_quality: quality,
    demo_prompt: buildDemoPrompt(lead, quality),
    outreach_body: buildOutreach({
      company: lead.company_name,
      contactName: lead.contact_name,
      city: lead.city,
      weakness: lead.weakness,
      demoUrl,
      channel: input.channel,
      niche: lead.niche
    }),
    outreach_sms: buildSmsOutreach(lead)
  };
}

function getBaseUrl(req: Request) {
  const requestOrigin = new URL(req.url).origin;
  const configured = process.env.APP_BASE_URL;
  if (!configured || configured.includes('localhost')) return requestOrigin;
  return configured;
}

function normalizeCampaignInput(body: Partial<CampaignInput>): CampaignInput {
  return {
    audience: (body.audience?.trim() || 'High-ticket local service businesses').slice(0, 300),
    locations: (body.locations?.trim() || '').slice(0, 2000),
    source: body.source || 'google_maps',
    sourcePayload: (body.sourcePayload || '').slice(0, 100_000),
    demoType: body.demoType || 'website',
    channel: body.channel || 'email',
    limit: Math.min(Math.max(Number(body.limit || 25), 1), 100),
    autoGenerateDemos: body.autoGenerateDemos === true,
    demoQuality: body.demoQuality === 'high' ? 'high' : 'low',
    demoProvider: 'v0',
    demoLimit: body.demoLimit === undefined ? undefined : Math.min(Math.max(Number(body.demoLimit), 0), 25),
    demoMinScore: body.demoMinScore === undefined ? undefined : Math.min(Math.max(Number(body.demoMinScore), 0), 100)
  };
}

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  mapper: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = [];
  let nextIndex = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (nextIndex < items.length) {
      const currentIndex = nextIndex;
      nextIndex += 1;
      results[currentIndex] = await mapper(items[currentIndex], currentIndex);
    }
  });
  await Promise.all(workers);
  return results;
}

function isMissingExtendedLeadColumn(message: string) {
  return /schema cache|column/i.test(message) && /(phone|address|rating|reviews_count|source_url|matched_keyword|instagram_url|demo_provider|outreach_sms)/i.test(message);
}

/**
 * Saved rows carry the client-generated UUIDs we inserted, so we can match
 * by id instead of relying on positional ordering.
 */
function mergeSavedLeadIds(savedLeads: Lead[], analyzedLeads: Lead[]): Lead[] {
  if (!savedLeads.length) return analyzedLeads;
  const savedById = new Map(savedLeads.map((lead) => [lead.id, lead]));
  return analyzedLeads.map((lead) => {
    const saved = savedById.get(lead.id);
    if (!saved) return lead;
    return {
      ...lead,
      id: saved.id,
      campaign_id: saved.campaign_id,
      created_at: saved.created_at
    };
  });
}

function shouldStreamToBigQuery(settings?: AppSettings) {
  return settings?.bigqueryEnabled !== false && process.env.BIGQUERY_ENABLED !== 'false';
}
