import { NextResponse } from 'next/server';
import { generateCampaignKeywordsAnthropic, analyzeLeadWithAnthropic } from '@/lib/anthropic';
import { discoverProspects } from '@/lib/discovery';
import { analyzeLeadWithGemini, generateCampaignKeywords } from '@/lib/gemini';
import { generateVertexCampaignKeywords, analyzeLeadWithVertex } from '@/lib/vertex';
import { streamLeadToBigQuery } from '@/lib/bigquery';
import { createDemoForLead, resolveDemoProvider } from '@/lib/demo-engine';
import { buildDemoPrompt, buildOutreach, buildPipeline, generateAlgorithmicKeywords } from '@/lib/pipeline';
import { applyPageSpeedAudit, runPageSpeedAudit } from '@/lib/pagespeed';
import { getSupabaseAdmin } from '@/lib/supabase';
import { applyWebsiteSnapshot, inspectWebsite } from '@/lib/website';
import { scrapeAndEnrichInstagramLead } from '@/lib/instagram';
import { buildSmsOutreach } from '@/lib/sms';
import type { AppSettings, CampaignInput, Lead } from '@/lib/types';

export async function GET() {
  const supabase = getSupabaseAdmin();
  if (!supabase) {
    return NextResponse.json({
      campaigns: [],
      leads: [],
      persistence: 'local_mock',
      message: 'Supabase env vars are not configured.'
    });
  }

  const { data: campaigns, error: campaignError } = await supabase
    .from('campaigns')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(20);
  if (campaignError) return NextResponse.json({ error: campaignError.message }, { status: 500 });

  const campaignIds = (campaigns || []).map((campaign) => campaign.id);
  const { data: leads, error: leadsError } = campaignIds.length
    ? await supabase.from('leads').select('*').in('campaign_id', campaignIds).order('created_at', { ascending: false })
    : { data: [], error: null };
  if (leadsError) return NextResponse.json({ error: leadsError.message }, { status: 500 });

  return NextResponse.json({ campaigns, leads, persistence: 'supabase' });
}

export async function POST(req: Request) {
  const body = (await req.json()) as Partial<CampaignInput> & { settings?: AppSettings };
  const input = normalizeCampaignInput(body);
  const settings = body.settings;
  const baseUrl = getBaseUrl(req);

  const aiProvider = settings?.aiProvider || 'gemini';
  const isVertexActive = aiProvider === 'vertex' || process.env.VERTEX_AI_ENABLED === 'true';
  const aiApiKey = settings?.aiApiKey || (aiProvider === 'anthropic' ? process.env.ANTHROPIC_API_KEY : process.env.GEMINI_API_KEY);
  const aiModel = settings?.aiModel;
  const aiEnabled = isVertexActive || (Boolean(aiApiKey) && (Boolean(settings?.aiApiKey) || process.env.GEMINI_ENABLED === 'true' || process.env.ANTHROPIC_ENABLED === 'true'));

  const v0ApiKey = settings?.v0ApiKey || process.env.V0_API_KEY;
  const demoProvider = resolveDemoProvider(input.demoProvider, settings);
  const autoGenerateDemos = input.autoGenerateDemos === true;
  const maxAutoDemos = Math.max(0, Math.min(input.demoLimit ?? settings?.maxAutoDemosPerCampaign ?? 3, 25));
  const minDemoScore = Math.max(0, Math.min(input.demoMinScore ?? settings?.minDemoScore ?? 75, 100));
  const canAutoGenerate =
    autoGenerateDemos &&
    maxAutoDemos > 0 &&
    (demoProvider === 'agentic' || Boolean(v0ApiKey));

  // Generate multi-keyword search queries for campaign scraping using configured AI model (Vertex AI, Gemini, or Anthropic)
  let keywords: string[] = [];
  if (aiEnabled) {
    try {
      if (isVertexActive) {
        keywords = await generateVertexCampaignKeywords(input, {
          projectId: settings?.gcpProjectId,
          location: settings?.gcpLocation,
          model: settings?.vertexModel || settings?.aiModel,
          enableGrounding: settings?.vertexGrounding
        });
      } else if (aiProvider === 'anthropic' && aiApiKey) {
        keywords = await generateCampaignKeywordsAnthropic(input.audience, input.locations, input.source, aiApiKey, aiModel);
      } else if (aiApiKey) {
        keywords = await generateCampaignKeywords(input.audience, input.locations, input.source, aiApiKey, aiModel);
      }
    } catch {
      keywords = [];
    }
  }
  if (keywords.length === 0) {
    keywords = generateAlgorithmicKeywords(input);
  }

  let discoveredProspects = [];
  try {
    discoveredProspects = await discoverProspects(input, keywords);
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Lead discovery failed.' },
      { status: 502 }
    );
  }

  const pipeline = buildPipeline(input, keywords, discoveredProspects);
  if (pipeline.leads.length === 0) {
    return NextResponse.json(
      {
        error:
          'No real leads found. Paste CSV/URL rows, use Google Maps with SERPAPI_KEY, or configure APIFY_ACTOR_ID/APIFY_TASK_ID for this source.'
      },
      { status: 400 }
    );
  }

  const inspectedLeads = await mapWithConcurrency(pipeline.leads, 4, async (lead) => {
    let current = lead;

    // 1. Inspect website if available
    const siteUrl = current.website_url;
    if (siteUrl) {
      const snapshot = await inspectWebsite(siteUrl);
      current = applyWebsiteSnapshot(current, snapshot);
      const pageSpeed = await runPageSpeedAudit(siteUrl, snapshot);
      current = applyPageSpeedAudit(current, pageSpeed);
    }

    // 2. Scrape & enrich Instagram if lead has an Instagram profile
    if (current.instagram_url) {
      current = await scrapeAndEnrichInstagramLead(current);
    }

    return refreshLeadArtifacts(current, input, baseUrl);
  });

  const analyzedLeads = await Promise.all(
    inspectedLeads.map(async (lead) => {
      if (!aiEnabled) return lead;
      try {
        let ai: Partial<Lead>;
        if (isVertexActive) {
          ai = await analyzeLeadWithVertex(lead, {
            projectId: settings?.gcpProjectId,
            location: settings?.gcpLocation,
            model: settings?.vertexModel || settings?.aiModel,
            enableGrounding: settings?.vertexGrounding
          });
        } else if (aiProvider === 'anthropic' && aiApiKey) {
          ai = await analyzeLeadWithAnthropic(lead, aiApiKey, aiModel);
        } else if (aiApiKey) {
          ai = await analyzeLeadWithGemini(lead, aiApiKey, aiModel);
        } else {
          return lead;
        }

        const merged = {
          ...lead,
          ...ai,
          status: typeof ai.fit_score === 'number' && ai.fit_score >= 70 ? ('qualified' as const) : lead.status,
          outreach_body:
            ai.outreach_body?.replace('{{demo_url}}', lead.demo_url || `${baseUrl}/demo/${lead.id}`) ||
            buildOutreach({
              company: lead.company_name,
              contactName: lead.contact_name,
              city: lead.city,
              weakness: ai.weakness || lead.weakness,
              demoUrl: lead.demo_url || `${baseUrl}/demo/${lead.id}`,
              channel: input.channel,
              niche: lead.niche
            })
        } satisfies Lead;
        return {
          ...merged,
          demo_prompt: buildDemoPrompt(merged)
        } satisfies Lead;
      } catch {
        return lead;
      }
    })
  );

  const contactEnrichedLeads = analyzedLeads.map((lead) => {
    const hasContact = Boolean(lead.email?.trim()) || Boolean(lead.phone?.trim()) || Boolean(lead.linkedin_url?.trim()) || Boolean(lead.instagram_url?.trim());

    if (!hasContact) {
      return {
        ...lead,
        status: 'skipped' as const,
        qualification_reason: 'Skipped: No contact email, phone number, or social handle found to reach prospect.',
        signals: [
          ...lead.signals.filter((s) => s.label !== 'Contact status'),
          { label: 'Contact status', value: 'Missing contact info', severity: 'critical' }
        ]
      } satisfies Lead;
    }

    const fitScore = typeof lead.fit_score === 'number' ? lead.fit_score : 50;
    const finalStatus = fitScore >= 70 ? ('qualified' as const) : ('scraped' as const);

    return {
      ...lead,
      status: finalStatus
    } satisfies Lead;
  });

  // Auto-generate demos only when explicitly enabled and inside the credit guardrails.
  let demoProcessedLeads: Lead[] = contactEnrichedLeads;
  if (canAutoGenerate) {
    let generatedCount = 0;
    demoProcessedLeads = await mapWithConcurrency(contactEnrichedLeads, demoProvider === 'agentic' ? 4 : 2, async (lead) => {
      if (lead.status !== 'qualified' || lead.fit_score < minDemoScore || generatedCount >= maxAutoDemos) return lead;
      generatedCount += 1;
      try {
        const demo = await createDemoForLead(lead, {
          settings,
          quality: input.demoQuality,
          provider: demoProvider,
          baseUrl
        });
        if (demo.status === 'ready' && demo.demoUrl) {
          const updated: Lead = {
            ...lead,
            status: 'demo_ready',
            demo_url: demo.demoUrl,
            demo_provider: demo.provider || demoProvider,
            demo_quality: input.demoQuality || 'low',
            demo_prompt: demo.demoArtifact || lead.demo_prompt,
            v0_chat_id: demo.chatId,
            v0_version_id: demo.versionId
          };
          return refreshLeadArtifacts(updated, input, baseUrl);
        }
      } catch {
        // Continue without blocking campaign creation
      }
      return lead;
    });
  }

  pipeline.leads = demoProcessedLeads;
  pipeline.campaign.qualified = demoProcessedLeads.filter((lead) => lead.fit_score >= 70).length;
  pipeline.campaign.demos_generated = demoProcessedLeads.filter((lead) => lead.status === 'demo_ready').length;

  const supabase = getSupabaseAdmin();
  if (!supabase) {
    return NextResponse.json({
      ...pipeline,
      persistence: 'local_mock',
      message: 'Supabase env vars are not configured, so this campaign was generated locally.'
    });
  }

  const { data: campaign, error: campaignError } = await supabase
    .from('campaigns')
    .insert({
      name: pipeline.campaign.name,
      audience: pipeline.campaign.audience,
      locations: pipeline.campaign.locations,
      source: pipeline.campaign.source,
      demo_type: pipeline.campaign.demo_type,
      channel: pipeline.campaign.channel,
      status: pipeline.campaign.status,
      total_prospects: pipeline.campaign.total_prospects,
      qualified: pipeline.campaign.qualified,
      demos_generated: pipeline.campaign.demos_generated
    })
    .select()
    .single();

  if (campaignError) {
    return NextResponse.json({ error: campaignError.message }, { status: 500 });
  }

  const leadsForPersistence = demoProcessedLeads.map((lead) =>
    refreshLeadArtifacts(
      {
        ...lead,
        id: crypto.randomUUID(),
        campaign_id: campaign.id
      },
      input,
      baseUrl
    )
  );

  const leadsToSave = leadsForPersistence.map((lead) => ({
    id: lead.id,
    campaign_id: campaign.id,
    company_name: lead.company_name,
    contact_name: lead.contact_name,
    niche: lead.niche,
    source: lead.source,
    website_url: lead.website_url,
    linkedin_url: lead.linkedin_url,
    instagram_url: lead.instagram_url,
    city: lead.city,
    email: lead.email,
    phone: lead.phone,
    address: lead.address,
    rating: lead.rating,
    reviews_count: lead.reviews_count,
    source_url: lead.source_url,
    status: lead.status,
    fit_score: lead.fit_score,
    weakness: lead.weakness,
    qualification_reason: lead.qualification_reason,
    signals: lead.signals,
    demo_type: lead.demo_type,
    demo_quality: lead.demo_quality || input.demoQuality || 'low',
    demo_prompt: lead.demo_prompt,
    demo_url: lead.demo_url,
    demo_provider: lead.demo_provider || demoProvider,
    v0_chat_id: lead.v0_chat_id,
    v0_version_id: lead.v0_version_id,
    outreach_subject: lead.outreach_subject,
    outreach_body: lead.outreach_body,
    outreach_sms: lead.outreach_sms,
    matched_keyword: lead.matched_keyword
  }));

  let { data: savedLeads, error: leadsError } = await supabase.from('leads').insert(leadsToSave).select();
  if (leadsError && isMissingExtendedLeadColumn(leadsError.message)) {
    const legacyLeadsToSave = leadsToSave.map(
      ({ phone, address, rating, reviews_count, source_url, matched_keyword, instagram_url, demo_quality, demo_provider, outreach_sms, ...legacyLead }) => legacyLead
    );
    const legacyResult = await supabase.from('leads').insert(legacyLeadsToSave).select();
    savedLeads = legacyResult.data;
    leadsError = legacyResult.error;
  }
  if (leadsError) {
    return NextResponse.json({ error: leadsError.message }, { status: 500 });
  }

  if (shouldStreamToBigQuery(settings)) {
    Promise.allSettled(leadsForPersistence.map((l) => streamLeadToBigQuery(l))).catch(() => {
      // Non-blocking background streaming
    });
  }

  return NextResponse.json({
    campaign: {
      ...campaign,
      keywords: pipeline.campaign.keywords,
      demos_generated: pipeline.campaign.demos_generated
    },
    leads: mergeSavedLeadIds(savedLeads || [], leadsForPersistence),
    persistence: 'supabase'
  });
}

function refreshLeadArtifacts(lead: Lead, input: CampaignInput, baseUrl: string): Lead {
  const demoUrl = lead.demo_url || `${baseUrl}/demo/${lead.id}`;
  const quality = lead.demo_quality || input.demoQuality || 'low';
  return {
    ...lead,
    demo_quality: quality,
    demo_prompt: buildDemoPrompt(lead, quality),
    outreach_body: buildOutreach({
      company: lead.company_name,
      contactName: lead.contact_name,
      city: lead.city,
      weakness: lead.weakness,
      demoUrl,
      channel: input.channel,
      niche: lead.niche
    }),
    outreach_sms: buildSmsOutreach(lead)
  };
}

function getBaseUrl(req: Request) {
  const requestOrigin = new URL(req.url).origin;
  const configured = process.env.APP_BASE_URL;
  if (!configured || configured.includes('localhost')) return requestOrigin;
  return configured;
}

function normalizeCampaignInput(body: Partial<CampaignInput>): CampaignInput {
  return {
    audience: body.audience?.trim() || 'High-ticket local service businesses',
    locations: body.locations?.trim() || '',
    source: body.source || 'google_maps',
    sourcePayload: body.sourcePayload || '',
    demoType: body.demoType || 'website',
    channel: body.channel || 'email',
    limit: Math.min(Math.max(Number(body.limit || 25), 1), 250),
    autoGenerateDemos: body.autoGenerateDemos === true,
    demoQuality: body.demoQuality === 'high' ? 'high' : 'low',
    demoProvider: body.demoProvider,
    demoLimit: body.demoLimit === undefined ? undefined : Math.min(Math.max(Number(body.demoLimit), 0), 25),
    demoMinScore: body.demoMinScore === undefined ? undefined : Math.min(Math.max(Number(body.demoMinScore), 0), 100)
  };
}

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  mapper: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = [];
  let nextIndex = 0;
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (nextIndex < items.length) {
      const currentIndex = nextIndex;
      nextIndex += 1;
      results[currentIndex] = await mapper(items[currentIndex], currentIndex);
    }
  });
  await Promise.all(workers);
  return results;
}

function isMissingExtendedLeadColumn(message: string) {
  return /schema cache|column/i.test(message) && /(phone|address|rating|reviews_count|source_url|matched_keyword|instagram_url|demo_provider|outreach_sms)/i.test(message);
}

function mergeSavedLeadIds(savedLeads: Lead[], analyzedLeads: Lead[]): Lead[] {
  if (!savedLeads.length) return analyzedLeads;
  return analyzedLeads.map((lead, index) => ({
    ...lead,
    id: savedLeads[index]?.id || lead.id,
    campaign_id: savedLeads[index]?.campaign_id || lead.campaign_id
  }));
}

function shouldStreamToBigQuery(settings?: AppSettings) {
  return settings?.bigqueryEnabled !== false && process.env.BIGQUERY_ENABLED !== 'false';
}
